### ISSUE TITLE
change the gnome menu color

### ISSUE THREAD

**Issue by Razzo1987** [fnxweb/gnome-shell-pi-hole#1]
with the extension enable the text color of the menu become lime:

![immagine](https://user-images.githubusercontent.com/906604/178775651-691279bd-0a80-4ea2-8966-ac52f8c2c1dc.png)

if i turn off the extension everything return normal

![immagine](https://user-images.githubusercontent.com/906604/178775599-59883626-a858-454f-944a-9a3d8c38f8f0.png)

**Comment by fnxweb** [comment]
Well that's jolly peculiar, extensions' settings shouldn't be able to leak out into the main shell like that.
What theme / config. do you have that's making the menu have a white background?  On my system, both light mode and dark mode give a light-on-dark system menu.

**Comment by fnxweb** [comment]
And I only have two colours in the extension stylesheet, white and grey.

**Comment by Razzo1987** [comment]
> Well that's jolly peculiar, extensions' settings shouldn't be able to leak out into the main shell like that. What theme / config. do you have that's making the menu have a white background? On my system, both light mode and dark mode give a light-on-dark system menu.

In dark mode there is not the issue:
![immagine](https://user-images.githubusercontent.com/906604/178793776-e96622d5-01b1-441a-afed-19e66590bc9b.png)

if you need some config file info can you send me the path?

**Comment by fnxweb** [comment]
I'm even more confused now;  my light mode (Fedora 36) still has dark background system menus.  What distro / release are you using to get light background menus?

**Comment by fnxweb** [comment]
Also, do you have the User Themes gnome-shell extension enabled (**Extensions**), and is there a user theme selected (**Gnome Tweaks / Appearance**)?

**Comment by Razzo1987** [comment]
I tried to replicate the problem in a virtualbox clear installation of ubuntu 22.04:

![image](https://user-images.githubusercontent.com/906604/178992527-d2f764f8-941c-4eec-b522-1848270cbdec.png)

only the default extensions are present

**Comment by fnxweb** [comment]
OK, I'll look at doing the same and get back to you.

**Comment by Razzo1987** [comment]
Thanks, really super helpful and quick to respond ;)
Good job

**Comment by fnxweb** [comment]
Yeah, well, hold your praise untiI find something!  I still can't even conceive of how the extension can pollute the main system menu!
At least if I can reproduce it I can tinker.

May be a few days though, wilting in the heat here.

**Comment by fnxweb** [comment]
OK, I think Ubuntu has done something funky with their default theme to get the white background working on light mode, which means that extension stylesheets all apply to everything.  I need to have a play to figure out how to be more explicit while doing the _right_ thing & catering for light and dark modes, if that's even possible.

In the short term, you can work around the problem by **deleting** the first **StLabel** block in:

> .local/share/gnome-shell/extensions/pi-hole@fnxweb.com/stylesheet.css

```
StLabel
{
  color: #ffffff;
}
```

Gawd knows how that makes everything else green, though!

**Comment by fnxweb** [comment]
Gah, while I think I can detect the light/dark mode setting, that of course doesn't help because we have wildly different light modes!  And I can't see a way of determining the current theme's background colour specification.

I'll have to add a specific light/dark mode switch that you can flick depending upon your actual theme's background colour.

**Comment by fnxweb** [comment]
Given up on colouring, I only need highlights, so can rearrange a bit to just do bold text and hopefully everything Just Works™.

**Comment by fnxweb** [comment]
The colouring for the first item doesn't look quite right for GNOME < 42, but that's not the end of the world.

**Comment by fnxweb** [comment]
Actually, the colouring's not great on stock GNOME 42 either, it only fully works on Ubuntu now, so I'll have to dig a little more.
But at least it doesn't corrupt all of Ubuntu's top bar now.  I've pushed that version to the extensions site.
