### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by InvisibleRasta** [fnxweb/gnome-shell-pi-hole#4]
Hello, could you add support for gnome 45

**Comment by fnxweb** [comment]
It's the intention, but I've not had time to download a VM with GNOME 45 in yet, and it sounds like it will require a significant rewrite (for all GNOME addons).

**Comment by fnxweb** [comment]
Resolved with commits
5ef7602d8cb4cbbb7ac8e59400c410bb1efe1d36
14165dfe511df66d7f4ac62824d378c37a5a84bc
f1d3eea6c1d6c42a91cb5ade47766b317b51fb29
