### ISSUE TITLE
Gnome 46

### ISSUE THREAD

**Issue by InvisibleRasta** [fnxweb/gnome-shell-pi-hole#5]
Could you add gnome 46 support?

**Comment by fnxweb** [comment]
It probably ought to just work, I wish GNOME had some way of being able to flag the version compatibility via the website issues of having to roll a whole new release just to bump the metadata.

Does it actually error, or just it only not running because of the claimed max version? You may be able to nobble it into life just by editing that locally until I can find a VM to test it in.

**Comment by InvisibleRasta** [comment]
I tried to change the version to 46 in metadata.json and  the error I am getting when enabling the plugin is the following:
`TypeError: menuitem.actor.add_actor is not a function`

**Comment by InvisibleRasta** [comment]
It seems it has to do with this 
```
    // Add an item to the “menu”
    addMenuItem(item)
    {
        let menuitem = new popupMenu.PopupBaseMenuItem({ reactive:false });
        menuitem.actor.add_actor( item );
        this.menu.addMenuItem( menuitem );
    }
```

**Comment by fnxweb** [comment]
Hmph. Their massive recent rejig was supposed to prevent this sort of nonsense.  I even recently added their lint config to warn me of iffy or deprecated usage. _<sigh>_

It'll be a few days before I can look into it, I've got some important DIY to sort out over this weekend.

**Comment by InvisibleRasta** [comment]
I actually got the extension to work by just commenting out:
` menuitem.actor.add_actor( item );`
Not sure what it is supposed to do but the extension is at least working now, at least the pause adn enable/disable are
EDIT: yeah it seems I disabled the status indicator, oh well for now it is more than enought for me, at least it works

**Comment by fnxweb** [comment]
Cool. I'll try to remember what that does!  May not be needed any more (hence it's removal). Alternatively it might be just something like “menuitem.add_actor…” now, they seem to have done that a lot.

**Comment by InvisibleRasta** [comment]
Just wanted to let you know that I fixed the extension and its fully working again  by changing   `menuitem.actor.add_actor( item );`  
to
`menuitem.actor.add_child( item );`

**Comment by fnxweb** [comment]
Great, thanks!
